# Generated by Django 5.2 on 2025-05-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='La empresa a la que pertenece este usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('superadmin', 'Administrador Global'), ('admin', 'Administrador de Empresa'), ('staff', 'Personal'), ('customer', 'Cliente')], default='customer', max_length=10),
        ),
    ]
