# Generated by Django 5.2 on 2025-06-22 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_package', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('in_progress', 'En curso'), ('completed', 'Finalizado'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('attendee_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='companies.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='locations.location')),
            ],
        ),
    ]
