# Generated by Django 5.2 on 2025-05-20 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_company'),
        ('packages', '0002_remove_package_created_at_remove_package_updated_at'),
        ('services', '0002_service_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='packages.package'),
        ),
        migrations.AlterField(
            model_name='event',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='events', to='services.service'),
        ),
    ]
