# Generated by Django 5.2 on 2025-06-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commercial_name', models.CharField(help_text='Nombre comercial del proveedor', max_length=200, verbose_name='Nombre comercial')),
                ('contact_name', models.CharField(help_text='Nombre de la persona de contacto principal', max_length=200, verbose_name='Nombre del contacto principal')),
                ('contact_phone', models.CharField(help_text='Teléfono de contacto del proveedor', max_length=20, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(help_text='Correo electrónico del proveedor', max_length=254, verbose_name='Correo electrónico')),
                ('website', models.URLField(blank=True, help_text='Sitio web del proveedor (opcional)', null=True, verbose_name='Sitio web')),
                ('address', models.TextField(blank=True, help_text='Dirección física del proveedor (opcional)', null=True, verbose_name='Dirección física')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el proveedor está activo', verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales sobre el proveedor', null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('company', models.ForeignKey(help_text='La empresa a la que pertenece este proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='companies.company')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'providers',
                'ordering': ['commercial_name'],
                'unique_together': {('company', 'commercial_name')},
            },
        ),
    ]
