# Generated by Django 5.2 on 2025-06-22 00:09

import django.db.models.deletion
import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('identity_document', models.CharField(help_text='DNI, cédula, pasaporte, etc.', max_length=50, verbose_name='Documento de identidad')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('birth_date', models.DateField(verbose_name='Fecha de nacimiento')),
                ('position', models.CharField(choices=[('tecnico', 'Técnico'), ('logistica', 'Logística'), ('seguridad', 'Seguridad'), ('coordinador', 'Coordinador'), ('catering', 'Catering'), ('audiovisual', 'Audiovisual'), ('limpieza', 'Limpieza'), ('decoracion', 'Decoración'), ('otro', 'Otro')], max_length=20, verbose_name='Puesto o rol')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=staff.models.staff_photo_path, verbose_name='Foto')),
                ('hire_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='La empresa a la que pertenece este personal', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='companies.company')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'staff',
                'ordering': ['full_name'],
                'unique_together': {('company', 'identity_document')},
            },
        ),
    ]
