# Generated by Django 5.2 on 2025-05-19 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='package',
            name='updated_at',
        ),
    ]
