# Generated by Django 5.2 on 2025-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_measure', models.CharField(choices=[('event', 'Por Evento'), ('hour', 'Por Hora'), ('person', 'Por Persona'), ('day', 'Por Día'), ('unit', 'Por Unidad')], default='event', max_length=10)),
                ('standard_duration', models.PositiveIntegerField(blank=True, help_text='Duración en minutos (si aplica)', null=True)),
                ('provider', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
