# Generated by Django 5.2 on 2025-06-22 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(help_text='Proveedor asignado al servicio', on_delete=django.db.models.deletion.CASCADE, related_name='services', to='providers.provider'),
        ),
    ]
