# Generated by Django 5.2 on 2025-04-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_content_type_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
