# Generated by Django 5.2 on 2025-06-02 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_logo_url_alter_company_website'),
        ('events', '0003_event_is_package_event_package_alter_event_services'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nombre o título de la tarea')),
                ('description', models.TextField(verbose_name='Descripción detallada')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fecha y hora de finalización')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado de la tarea')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas o instrucciones adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ManyToManyField(blank=True, help_text='Personal asignado a esta tarea', related_name='assigned_tasks', to='staff.staff', verbose_name='Responsables')),
                ('company', models.ForeignKey(help_text='La empresa a la que pertenece esta tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='companies.company')),
                ('event', models.ForeignKey(blank=True, help_text='Evento al que pertenece esta tarea (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tasks',
                'ordering': ['start_datetime'],
            },
        ),
    ]
