# Generated by Django 5.2 on 2025-06-22 00:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('monthly', 'Mensual'), ('biannual', 'Semestral'), ('annual', 'Anual')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('past_due', 'Pago pendiente'), ('canceled', 'Cancelada'), ('incomplete', 'Incompleta'), ('incomplete_expired', 'Incompleta expirada'), ('trialing', 'En periodo de prueba'), ('unpaid', 'No pagada')], default='incomplete', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
