# Generated by Django 5.2 on 2025-06-23 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name='Nombre del Invitado')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email del Invitado')),
                ('guest_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono del Invitado')),
                ('invitation_type', models.CharField(choices=[('familia', 'Familia'), ('general', 'General'), ('trabajo', 'Trabajo'), ('amigos', 'Amigos')], default='general', max_length=20, verbose_name='Tipo de Invitación')),
                ('custom_message', models.TextField(blank=True, help_text='Mensaje personalizado para el invitado', null=True, verbose_name='Mensaje para el Invitado')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado de la Invitación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('confirmation_token', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token de Confirmación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'guest_email')},
            },
        ),
    ]
