# Generated by Django 5.2 on 2025-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='assigned_seats',
            field=models.CharField(blank=True, help_text='Asientos separados por comas, ej: A-1,A-2,A-3', max_length=500, null=True, verbose_name='Asientos Asignados'),
        ),
    ]
