# Generated by Django 5.2 on 2025-06-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad (personas)')),
                ('location_type', models.CharField(choices=[('salon', 'Salón'), ('jardin', 'Jardín'), ('playa', 'Playa'), ('auditorio', 'Auditorio'), ('terraza', 'Terraza'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de locación')),
                ('rental_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de alquiler')),
                ('price_unit', models.CharField(choices=[('event', 'Por Evento'), ('hour', 'Por Hora'), ('day', 'Por Día')], default='event', max_length=10, verbose_name='Unidad de medida del precio')),
                ('area_sqm', models.PositiveIntegerField(verbose_name='Área (m²)')),
                ('parking_spaces', models.PositiveIntegerField(verbose_name='Estacionamiento (vehículos)')),
                ('environment_type', models.CharField(choices=[('cerrado', 'Cerrado'), ('abierto', 'Abierto'), ('semiabierto', 'Semiabierto')], max_length=15, verbose_name='Tipo de ambiente')),
                ('extra_hour_cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Costo por hora extra')),
                ('provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor asociado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.company')),
            ],
            options={
                'verbose_name': 'Locación',
                'verbose_name_plural': 'Locaciones',
            },
        ),
    ]
