# Generated by Django 5.2 on 2025-06-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Hora de inicio del cronograma')),
                ('end_time', models.TimeField(help_text='Hora de finalización del cronograma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='companies.company')),
                ('event', models.OneToOneField(help_text='Evento al que pertenece este cronograma', on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='events.event')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
                'ordering': ['event__start_date'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nombre o título de la actividad', max_length=200)),
                ('description', models.TextField(help_text='Descripción detallada de la actividad')),
                ('start_time', models.TimeField(help_text='Hora de inicio de la actividad')),
                ('end_time', models.TimeField(help_text='Hora de finalización de la actividad')),
                ('status', models.CharField(choices=[('planificada', 'Planificada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', help_text='Estado actual de la actividad', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(help_text='Cronograma al que pertenece esta actividad', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='schedules.schedule')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['start_time', 'end_time'],
            },
        ),
    ]
