# Generated by Django 5.2 on 2025-06-22 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notaventa',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_venta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallenotaventa',
            name='nota_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.notaventa'),
        ),
    ]
