# Generated by Django 5.2 on 2025-06-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaventa',
            name='correo_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
